// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLhlfYNLMg8hmH2e5n8d6kggUfQflQOMg',
    appId: '1:839050009459:web:f6134075a0bc01895f4306',
    messagingSenderId: '839050009459',
    projectId: 'mandi-trade-portal',
    authDomain: 'mandi-trade-portal.firebaseapp.com',
    storageBucket: 'mandi-trade-portal.firebasestorage.app',
    measurementId: 'G-WEQ90MCKK0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfWTJfwfyRwPQJG8-S0hNWhENU8oTyy7Y',
    appId: '1:839050009459:android:d3f202eb14f267665f4306',
    messagingSenderId: '839050009459',
    projectId: 'mandi-trade-portal',
    storageBucket: 'mandi-trade-portal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBij-0kLBE3Md749BirxHuJoY5-8Yvm40o',
    appId: '1:839050009459:ios:0f078483cf870c1d5f4306',
    messagingSenderId: '839050009459',
    projectId: 'mandi-trade-portal',
    storageBucket: 'mandi-trade-portal.firebasestorage.app',
    iosBundleId: 'com.example.mandiBrokerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBij-0kLBE3Md749BirxHuJoY5-8Yvm40o',
    appId: '1:839050009459:ios:0f078483cf870c1d5f4306',
    messagingSenderId: '839050009459',
    projectId: 'mandi-trade-portal',
    storageBucket: 'mandi-trade-portal.firebasestorage.app',
    iosBundleId: 'com.example.mandiBrokerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLhlfYNLMg8hmH2e5n8d6kggUfQflQOMg',
    appId: '1:839050009459:web:42f009a77b035e7a5f4306',
    messagingSenderId: '839050009459',
    projectId: 'mandi-trade-portal',
    authDomain: 'mandi-trade-portal.firebaseapp.com',
    storageBucket: 'mandi-trade-portal.firebasestorage.app',
    measurementId: 'G-J1HH25WFTJ',
  );
}
